### ISSUE TITLE
[BUG] - Crash when i hit show the toast twice while the other hasn't dismissed

### ISSUE THREAD

**Issue by DavidAmunga** [gunnartorfis/sonner-native#74] opened 2024-09-10 14:37 UTC
**Describe the bug**
App crashes when i try to show the toast twice 

**To Reproduce**

1. Setup a handler New Button
``` 
<Button onPress={()=>{ toast("This Alert") }}>
Click me
</Button
```
2. Click it.
3. Click it again before the current one disappears.
4. See the error
**Expected behavior**
Should show a stack of alerts in the screen vertically.

**Screenshots**
![image](https://github.com/user-attachments/assets/72d86388-35ef-4e2c-8402-48a916a10343)

**Environment info**

| Library                      | Version |
| ---------------------------- | ------- |
| sonner-native                | ^0.9.1   |
| react-native                 | 0.74.5   |
| react-native-reanimated      | ~3.10.1   |
| react-native-gesture-handler | ~2.16.1   |
| nativewind                    |^4.0.36 |

**Additional context**
Currently using Expo(~51.0.26) & Expo Router.

Stacked my Root Layout like this
```js
  <ThemeProvider value={LIGHT_THEME}>
        <SafeAreaProvider>
          <GestureHandlerRootView style={{ flex: 1 }}>
            <StatusBar backgroundColor="#EEEDEB" style={"dark"} />
            <Stack screenOptions={{ headerShown: false }}>
              <Stack.Screen name="(app)" options={{ headerShown: false }} />
              <Stack.Screen name="(auth)" options={{ headerShown: false }} />
              <Stack.Screen name="index" options={{ headerShown: false }} />
            </Stack>
            <Toaster
              theme="light"
              toastOptions={{
                style: { backgroundColor: "white" },
                className: "bg-white border rounded-md",
              }}
            />
          </GestureHandlerRootView>
        </SafeAreaProvider>
        <PortalHost />
      </ThemeProvider> 
```

**Comment by gunnartorfis** [comment] 2024-09-10 19:11
@DavidAmunga could you check if updating to the latest version (0.10.0) fixes that? If not, if you could share with me a link to a minimum reproducible on GitHub that's speed things up, I'm unable to reproduce this myself.

**Comment by gunnartorfis** [comment] 2024-09-10 20:05
Possible duplicate of #49

**Comment by gunnartorfis** [comment] 2024-09-14 07:49
Marking as duplicate for now.

**Closed by gunnartorfis** 2024-09-14 07:49 UTC
Labels: bug, needs more info
